[package]
name = "tokio-postgres-tls"
description = "Rustls integration for tokio-postgres"
version = "0.12.0"
authors = ["Jasper Hugo <jasper@jasperhugo.com>"]
repository = "https://github.com/i18n-now/tokio-postgres-tls"
edition = "2018"
license = "MIT"
readme = "README.md"

[dependencies]
ring = { version = "0.17", default-features = false }
rustls = { version = "0.23", default-features = false }
tokio = { version = "1", default-features = false }
tokio-postgres = { git = "https://github.com/lucannez64/rust-postgres.git", rev = "446bbc4", default-features = false }
tokio-rustls = { version = "0.26", default-features = false }
x509-certificate = { version = "0.23", default-features = false }

[dev-dependencies]
env_logger = { version = "0.11", default-features = false }
tokio = { version = "1", default-features = false, features = ["macros", "rt"] }
tokio-postgres = { git = "https://github.com/lucannez64/rust-postgres.git", rev = "446bbc4", default-features = false, features = [
  "runtime",
] }
rustls = { version = "0.23", default-features = false, features = [
  "std",
  "logging",
  "tls12",
  "ring",
] }
